# Generated by Django 3.0.8 on 2020-08-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
    ]
