# Generated by Django 3.0.8 on 2020-08-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_user_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='birthday',
            new_name='date_of_birth',
        ),
    ]
