# Generated by Django 3.0.8 on 2020-09-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20200905_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shopping.Listing'),
        ),
    ]
