# Generated by Django 3.0.8 on 2020-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_auto_20200905_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
