# Generated by Django 3.0.8 on 2020-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_user_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
