# Generated by Django 3.0.8 on 2020-08-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('desrc', models.TextField()),
                ('category', models.CharField(blank=True, choices=[("Men's Wear", "Men's Wear"), ("Women's Apparel", "Women's Apparel"), ('Mobile & Gadgets', 'Mobile & Gadgets'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Home Appliances', 'Home Appliances'), ('Home & Living', 'Home & Living'), ('Kids Fashion', 'Kids Fashion'), ('Toys, Kids & Babies', 'Toys, Kids & Babies'), ('Video Games', 'Video Games'), ('Food & Beverages', 'Food & Beverages'), ('Computers & Peripherals', 'Computers & Peripherals'), ('Hobbies & Books', 'Hobbies & Books'), ('Health & Wellness', 'Health & Wellness'), ("Women's Bags", "Women's Bags"), ('Travel & Luggage', 'Travel & Luggage'), ('Pet Food & Supplies', 'Pet Food & Supplies'), ('Watches', 'Watches'), ('Jewellery & Accessory', 'Jewellery & Accessory'), ("Men's Shoes", "Men's Shoes"), ("Women's Shoes", "Women's Shoes"), ('Sports & Outdoors', 'Sports & Outdoors'), ('Automotive', 'Automotive'), ("Men's Bags", "Men's Bags"), ('Cameras & Drones', 'Cameras & Drones'), ('Dining, Travel & Services', 'Dining, Travel & Services'), ('Miscellaneous', 'Miscellaneous')], max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shopping.Listing')),
            ],
        ),
    ]
