# Generated by Django 3.0.8 on 2020-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_listing_listingimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingimage',
            old_name='image_file',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
