# Generated by Django 3.0.8 on 2020-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('To Ship', 'To Ship'), ('To Receive', 'To Receive'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return/Refund', 'Return/Refund')], default='To Ship', max_length=64),
        ),
    ]
