# Generated by Django 3.0.8 on 2020-09-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20200913_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='has_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
