# Generated by Django 3.0.8 on 2020-08-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20200826_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
