# Generated by Django 3.0.8 on 2020-08-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_auto_20200826_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_main_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
