# Generated by Django 3.0.8 on 2020-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_auto_20200917_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date',
        ),
        migrations.AddField(
            model_name='listing',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
