# Generated by Django 3.0.8 on 2020-09-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_review_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating_score',
            field=models.IntegerField(default=0),
        ),
    ]
