# Generated by Django 3.0.8 on 2020-09-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0021_order_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
