# Generated by Django 3.0.8 on 2020-09-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_profile_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('To Ship', 'To Ship'), ('To Receive', 'To Receive'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return/Refund', 'Return/Refund')], max_length=64, null=True),
        ),
    ]
