# Generated by Django 3.0.8 on 2020-09-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.AddField(
            model_name='notification',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
