# Generated by Django 3.0.8 on 2020-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_auto_20200916_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='has_action',
            field=models.BooleanField(default=False),
        ),
    ]
