# Generated by Django 3.0.8 on 2020-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_auto_20200916_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_new_notification',
            field=models.BooleanField(default=False),
        ),
    ]
