# Generated by Django 3.0.8 on 2020-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_user_has_new_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_tracking',
            field=models.BooleanField(default=False),
        ),
    ]
