# Generated by Django 3.0.8 on 2020-09-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0018_order_is_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
        migrations.AddField(
            model_name='review',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
