# Generated by Django 3.0.8 on 2020-07-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_user_watchlist_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
