# Generated by Django 3.0.8 on 2020-07-30 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_has_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchlist_listing',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
