# Generated by Django 3.0.8 on 2020-07-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200727_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='bid',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='auctions.Listing'),
        ),
    ]
