# Generated by Django 3.0.8 on 2020-07-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_on_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
